### ISSUE TITLE
Unable to install 😭

### ISSUE THREAD

**Issue by lologhi** [lucapasquale/insomnia-plugin-chance#1]
Hi!
Thank you for this much needed plugin 👍 

In Insomnia, I did a "Copy Path", then paste it in the field next to "Install Plugin" button. Then I have this nice message: 

```
/Users/laurentgh/Library/Application Support/Insomnia/plugins/node_modules/insomnia-plugin-chance install error: Command failed: /Applications/Insomnia.app/Contents/Frameworks/Insomnia Helper.app/Contents/MacOS/Insomnia Helper /Applications/Insomnia.app/Contents/Resources/bin/yarn-standalone.js info /Users/laurentgh/Library/Application Support/Insomnia/plugins/node_modules/insomnia-plugin-chance --json
{"type":"error","data":"Could not write file \"/yarn-error.log\": \"EACCES: permission denied, open '/yarn-error.log'\""}
{"type":"error","data":"An unexpected error occurred: \"Invalid attempt to destructure non-iterable instance\"."}
```

I don't know what to do with that 😅
Thank you for your help!

**Comment by lucapasquale** [comment]
Weird, just tried here (Ubuntu) and it worked.

Try deleting the `insomnia-plugin-chance` folder where Insomnia stores all the plugins and try again, maybe with the new update I've made it fixed it :smile:

**Comment by lologhi** [comment]
Sorry, it was working well, my bad!
