### ISSUE TITLE
Value in options disables done button in inva

### ISSUE THREAD

**Issue by celroid** [lucapasquale/insomnia-plugin-chance#7]
I needed a random string to be generated each time i made a request, I've tried this plugin for that but because of that error that you know of in the README.md I cannot save the environment.

![image](https://user-images.githubusercontent.com/18095088/68395332-2cf24680-0178-11ea-87f6-a35a2adcbf94.png)

![image](https://user-images.githubusercontent.com/18095088/68395306-206dee00-0178-11ea-840b-92ec80e33c83.png)

**Comment by lucapasquale** [comment]
I've just published version `1.3.0`, and changed the way it handles the arguments. 
 Can you check if it works for your case?

Thanks

**Comment by celroid** [comment]
I wasn't notified by email about a reply to this post, I will check if it works soon. Thanks for working on it
